services:
  db:
    image: postgres:16
    container_name: task-tracker-db
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - taskdb_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-tracker-backend
    restart: always
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=taskdb;Username=postgres;Password=postgres
    ports:
      - "5001:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-tracker-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  taskdb_data: